import os

BOT_TOKEN = "8795699641:AAH2HprXisO7i7fPzZlBMZO28cZOTyQAZSU"

ADMIN_ID = "8469175911"

QR_IMAGE = "qr.png"

UPI_ID = "yourupi@upi"

CHANNEL_URL = "https://t.me/YOUR_CHANNEL"

ADMIN_USERNAME = os.getenv(
    "ADMIN_USERNAME",
    "YOUR_USERNAME"
)
